---
config:
  theme: mc
  look: classic
  layout: fixed
---
flowchart TD
    B("Iphone") --> n5["ReprodutorMusical"] & n6["NavegadorInternet"] & n7["AparelhoTelefonico"]
    n5 --> n8["-verificarConexao()<br>+tocarMusica()<br>+pularMusica()<br>+pausarMusica()<br>+voltarMusica()"]
    n6 --> n9["-verificarConexao()<br>-verificarHistorico()<br>+abrirGuia()<br>+fecharGuia()"]
    n7 --> n10["+ligar(String numero)
<br>&nbsp;+atender()
<br>&nbsp;+iniciarCorreioVoz()<br>"]
